# Generated by Django 4.0.2 on 2022-04-27 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studdybuddy', '0002_studydate_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studydate',
            old_name='subject',
            new_name='description',
        ),
    ]
