# Generated by Django 4.0.2 on 2022-04-27 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studdybuddy', '0003_rename_subject_studydate_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studydate',
            name='course',
            field=models.CharField(default='', max_length=50),
        ),
    ]
